layout_spectrum: 0.1602641
typography_spectrum: 0.3208248
color:
  saturation: 0.176315
  lightness: 0.7525522
  brandStrength: 0.6085281
  rhythmicContrast: 0.4563863
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: chemix
